<a href="https://colab.research.google.com/github/NarendarB0152/DataScience/blob/main/NLP/BOW/BOW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import pandas as pd
import numpy as np

In [52]:
df=pd.read_csv("spam1.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

\df.Category.value_counts()

In [53]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [54]:
df.shape

(5572, 3)

In [55]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [56]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [57]:
X_train.shape

(4457,)

In [58]:
X_test.shape

(1115,)

In [59]:
X_train[:4]

4996    Just looked it up and addie goes back Monday, ...
3206    Oh, yes, I've just been a little under the wea...
4400    Yes just finished watching days of our lives. ...
4915    You've already got a flaky parent. It'snot sup...
Name: Message, dtype: object

In [67]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59546 stored elements and shape (4457, 7791)>

In [68]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [69]:
v.get_feature_names_out()[1771]

'cheered'

In [63]:
v.vocabulary_

{'just': 3900,
 'looked': 4219,
 'it': 3791,
 'up': 7229,
 'and': 961,
 'addie': 812,
 'goes': 3197,
 'back': 1201,
 'monday': 4588,
 'sucks': 6619,
 'to': 6979,
 'be': 1280,
 'her': 3441,
 'oh': 4940,
 'yes': 7735,
 've': 7309,
 'been': 1301,
 'little': 4174,
 'under': 7188,
 'the': 6858,
 'weather': 7472,
 'so': 6328,
 'kind': 3963,
 'of': 4918,
 'coccooning': 1888,
 'at': 1121,
 'home': 3503,
 'finished': 2887,
 'watching': 7450,
 'days': 2192,
 'our': 5037,
 'lives': 4179,
 'love': 4245,
 'you': 7751,
 'already': 924,
 'got': 3230,
 'flaky': 2909,
 'parent': 5111,
 'snot': 6322,
 'supposed': 6668,
 'child': 1795,
 'job': 3860,
 'support': 6665,
 'not': 4852,
 'until': 7228,
 'they': 6884,
 're': 5621,
 'ride': 5818,
 'age': 863,
 'anyway': 1006,
 'there': 6876,
 'now': 4864,
 'hurt': 3591,
 'unintentional': 7203,
 'but': 1588,
 'nonetheless': 4835,
 'am': 936,
 'in': 3673,
 'escape': 2658,
 'theatre': 6862,
 'going': 3202,
 'watch': 7447,
 'kavalan': 3927,
 'few': 2843,
 'minutes':

In [70]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [71]:
np.where(X_train_np[0]!=0)

(array([ 812,  961, 1201, 1280, 3197, 3441, 3791, 3900, 4219, 4588, 6619,
        6979, 7229]),)

In [72]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [73]:
X_test_cv=v.transform(X_test)

In [74]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       961
           1       0.99      0.92      0.95       154

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [75]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])